### PR TITLE
plantball

### PR DESCRIPTION
**Pull request by DarknessShadow**
Sugar cane cannot be made into plantballs.

@Blood-Asp Is that a gregtech problem?

### CODE REVIEW

**Comment by Timeslice42** [comment]
Saplings give two plantballs, all other plant material gives one. Update your PR with these values and it should be good.

**Comment by Blood-Asp** [comment]
All the plantball recipes should be native IC2 recipes. I only added more recipes for other mods like extrabiomesXL.

**Comment by Timeslice42** [comment]
Actually, I forgot these were all moved to the compressor. There should be no crafting table recipes for plantballs. Reeds do need to have a recipe added to the compressor though.

**Comment by Timeslice42** [comment]
If you change IC2.ini and change lines 138 and 139 to this, it should fix it all:
```
; Format: <name>[@metadata], e.g. minecraft:bucket to disable IC2's bucket recipe from tin.
disable = IC2:blockMachine2@9,IC2:itemToolCutter,IC2:itemFuelPlantBall
```

**Comment by Timeslice42** [comment]
It would also be cool if you put the 'plantball' and 'sapling' vars in alphabetical order like everything else Jason has done...

**Comment by DarknessShadow** [comment]
something isnt right with teh ic2.ini ...

**Comment by Timeslice42** [comment]
Yeah, I don't know what that was all about, but it looks good now.

**Comment by DarknessShadow** [comment]
oops wrong order https://github.com/DarknessShadow/InfiTech-1.7/blob/5239754d87112382c6eccb3ca7e5801fb9030f23/scripts/gt_ic2.zs#L97-L98

**Comment by Timeslice42** [comment]
And if it hadn't been for those meddling kids, no one would have ever known! :P

**Pull request merged**
