### PR TITLE
Thaumcraft overhaul

### PR DESCRIPTION
**Pull request by Xavion3**
A pull request to manage the thaumcraft overhaul. Just read the changelog in thaumcraft.zs to get an idea, you should also be able to load the scripts fine, just so long as you have witching gadgets and the newest version of infinity core. Changes and integration across pretty much all of the mod, perfectly willing to answer any questions on it and listen to ideas, although it should be basically done at this point.

### CODE REVIEW

**Comment by JasonMcRay** [comment]
So it can be considered as finished, or are there some more bits to be done about it (except the witching gadgets addition)

**Comment by Xavion3** [comment]
Still some bits that need doing, got to go through and add recipes for thaumic tinker enchants for example.

**Comment by Xavion3** [comment]
Realized I forgot the adamantium dust disabling and that the travelers boots need to change thanks to the pneumaticraft overhaul making them much harder. So not quite done.

**Comment by Xavion3** [comment]
Now it should be done, although you'll probably want to test the scripts at some point in case I forgot some me specific change or something.

**Comment by JasonMcRay** [comment]
After initial look I havent found anything problematic (except the problem with reloading script, which hopefully will get fixed soon). I guess the best testing of the script will be in real play with the release.

**Pull request merged**
