### PR TITLE
Fix new clusters needing the wrong ores

### PR DESCRIPTION
**Pull request by Xavion3**

### CODE REVIEW

**Comment by yznpku** [comment]
Oh, by the way, please disable the inferno blast furnace recipes for the new clusters. They are showing in the NEI.

**Comment by JasonMcRay** [comment]
I don't think that NEI showing Infernal Blast Furnace recipes is possible to get rid of.

Its the same as with Rolling Machine from Railcraft. That block is disabled, and fully removed from game, but the recipes still show

**Comment by yznpku** [comment]
They can be disabled  #with
`mods.witchinggadgets.InfernalBlastfurnace.removeRecipe(_cluster_)`

See 9ca0fb29c772c9f0b8fd230f0c7aa55d43f76d8e.

**Comment by JasonMcRay** [comment]
Oh right.. I see...

2016-06-09 17:42 GMT+02:00 yznpku <notifications@github.com>:

**Comment by zeyad001** [comment]
Lithium Clusters also  macerate to beryllium dust, NEI reports regular smelting and infernal furnace to return normal lithium ingots though.

**Comment by Xavion3** [comment]
Really? Whoops, let me just fix that.

**Pull request merged**
