### PR TITLE
charcoal tooltip

### PR DESCRIPTION
**Pull request by DarknessShadow**
I think this would help some new players.

### CODE REVIEW

**Comment by yznpku** [comment]
I come to think of the time when people were confused about "how to craft an iron pickaxe". 
LOLOLOLOLOLOLOL

**Comment by JasonMcRay** [comment]
To help new players we have the quest book.

**Comment by DarknessShadow** [comment]
oh right forgot about the book :D

**Comment by Timeslice42** [comment]
Why not both?

**Pull request closed without merging**
