### PR TITLE
Fix mana beans and crystallized essence not scanning

### PR DESCRIPTION
**Pull request by Xavion3**

### CODE REVIEW

**Comment by DarknessShadow** [comment]
That fix only works for herba mana beans and all other mana beans have an additional 1 herba on them.
<a href="http://imgur.com/kXu0ZpQ.png"></a>
<a href="http://imgur.com/eQ1eZA4.png"></a>

**Comment by Xavion3** [comment]
No, see the lack of a 1? That means it doesn't have 1 herba, it has an extra *zero* herba. As in the herba is purely cosmetic, why does it have herba? It's a bean and I needed something to get it to work for me. It doesn't even give you extra research points on scanning, I tested.

So basically the options are use this and have an extra zero herba show up on mana beans and virtues on crystallised essentia, work out another solution, or just leave it as is where it doesn't work.

**Comment by DarknessShadow** [comment]
I tested it and it gave me 1 herba in the alchemical furnace.

**Comment by Xavion3** [comment]
That is what herba mana beans do yes, and my tests all have them only giving one of the correct aspect so if you have more evidence please provide it.

**Comment by DarknessShadow** [comment]
Why should I lie about this?
<a href="http://imgur.com/LSodeDD.gifv">https://www.youtube.com/watch?v=6dyi2Az-1fU&feature=youtu.be</a>

**Comment by Xavion3** [comment]
I'm stumped then as it works perfectly for me, no herba appearing. Guess it's a bust though.

**Pull request closed without merging**
