### PR TITLE
Rebalance tin can recipe

### PR DESCRIPTION
**Pull request by Timeslice42**
Part of #569

### CODE REVIEW

**Comment by Timeslice42** [comment]
Okay, this should be good to merge now.

**Comment by DarknessShadow** [comment]
Why did you remove the plantball recipes?

**Comment by Xavion3** [comment]
They didn't, in fact trawling through the commits I think you removed the plant ball recipe in https://github.com/JasonMcRay/InfiTech-1.7/commit/e9cd777e02d7617caaab1ddfad25f7f355b36578

**Comment by Timeslice42** [comment]
The plantballs were moved to the compressor, remember?

**Comment by JasonMcRay** [comment]
I think he meant you removed the compressor recipes from the script

**Pull request merged**
