### PR TITLE
allow everyone onto spacestation

### PR DESCRIPTION
**Pull request by DarknessShadow**
I think it would be cool to give everyone the possibility of visiting all spacestations without using /ssinvite.

### CODE REVIEW

**Comment by groveham** [comment]
I don't think this is a good idea because people build the space stations to be away from main worlds and it's adds a layer of protection as no one else can get there unless invited. 

I know that me and other server owners could turn it off it we wanted but I think it's left off by default and turned on by who specifically wants it if possible. 

What may be a good idea is the abillity to create public spacestations, maybe an option in the mod where instead of explicitally setting it for everyone that this is disabled (or enabled), a command can be added, something like "/ssPublic Allow"  and  "/ss Public Deny" so people can choose for themselves if they'd like theirs visited.
This would it also allows for Admin Spacestations that can be used for what ever you want, a Market, or even a basis for players to re-fuel and try for outer planets.

**Comment by DarknessShadow** [comment]
I don't think you have to worry to much about griefing on a space station because someone who is already playing for a month or longer on a server he wont suddenly start to grief and risk getting a ban. Furthermore you can just as easily use the protection tools on the space station that are available in the overworld.

The idea with "/ssPublic Allow" and "/ss Public Deny" commands would be nice.

**Comment by JasonMcRay** [comment]
It will stay as it is now. Reason of spacestations is to get away from everyone. However I posted a suggestion to have a command that will allow everyone on certain spacestation, if the creator will want to.

**Comment by JasonMcRay** [comment]
And its being taken care of. There will be a command available /ssinvite +all (-all) with some more additions.

**Pull request closed without merging**
