### PR TITLE
[New Mod] Steve's Carts

### PR DESCRIPTION
**Pull request by JasonMcRay**
Thanks @DarknessShadow

### CODE REVIEW

**Comment by JasonMcRay** [comment]
- reinforced metal + eye of galgador + possibly molten glowstone in a blast furnace for hot galgador metal

**Comment by JasonMcRay** [comment]
- lower the cost of exe of galgador to something not that insane

**Comment by DarknessShadow** [comment]
Was it your intention to take the older version of the file from 28 Sep 2015 instead of newest from 21 Nov 2015?
https://github.com/DarknessShadow/InfiTech-1.7/blob/b707fc684d9996ff543fc26524d89ac785f61d24/scripts/stevescarts2.zs
https://github.com/DarknessShadow/InfiTech-1.7/blob/1c4366daec47ce7e9da0ee6861a36c21048ea83e/scripts/stevescarts2.zs

Btw to the old thread.
I thought galgadorian stuff should be something you can do when you are already at the end because the basic and hardend things can do the same but with durability and less radius.
Netherstars aren't that expensive once you have a powered skeleton spawner in the nether and autokil (btw wither kills can be automated with drones and tesla coils).
The miner work with gregtech ores. The only problem is the ore detector which should recognize ores in the walls of the cave and mine them too but that doesn't work (not really important maybe a tooltip info necessary).
@Timeslice42 and @Xavion3 you can both make changes to it as you like because I have lots of stuff to do irl so I can't make anything.

**Comment by JasonMcRay** [comment]
To be fair, the Galgadorian metal was quite really in the end, where i don't think anyone would bother to make those. We are not going "kirara" or "New Horizons" pack ways. So it is fine with being little bit cheaper :)

**Comment by Xavion3** [comment]
By the way, I wrote some scripts for this, been fiddling with things. I'll put them up once I fiddle with a few more recipes, rebalanced things a bit and made some stuff need GT machines to make.

**Comment by Xavion3** [comment]
[stevescarts2.zs](https://github.com/JasonMcRay/InfiTech-1.7/files/126314/stevescarts2.txt)

There's what I did, fiddles with most of the recipes that were already being fiddled with but doesn't touch much else. Not adjusted for infinitycore or the like so can't just be dropped straight in.

**Comment by JasonMcRay** [comment]
@Xavion3 If you mean the Hot Galgadorian Metal... <<InfinityCore:itemMaterial:12>> :)

**Comment by JasonMcRay** [comment]
Checked the script and looks fine. I have added few extra bits. @Xavion3 Do you think it can now be merged, or is there something on your mind still?

**Comment by Xavion3** [comment]
Yeah this should be fine, you could go through and change everything slightly if you really wanted but it really is unneeded.

**Comment by DarknessShadow** [comment]
Just a quick question:
We don't have twilight forrest so how do we get fiery blood? https://github.com/JasonMcRay/InfiTech-1.7/blob/master/scripts/stevescarts2.zs#L524-L525

**Comment by JasonMcRay** [comment]
Magic

**Comment by Timeslice42** [comment]
And by magic he means thaumcraft.

**Pull request merged**
