### PR TITLE
vanilla saplings cannot be made into plantballs

### PR DESCRIPTION
**Pull request by DarknessShadow**
fixed

### CODE REVIEW

**Comment by Blood-Asp** [comment]
Is that a IT2 only bug, or should you better have reported it to me?

**Comment by DarknessShadow** [comment]
I don't know.

**Comment by Blood-Asp** [comment]
The way to do it should really be to catch the error as far up as possible. 

Just looked at GT in my dev enviroment and sapling recipe is also missing there. So it is something to fix on my side. This MT script should be at best tempoary until GT fixes it.

**Comment by DarknessShadow** [comment]
How can we figure out if its a modpack problem or gregtech problem? Always disable all other mods when we find stuff like that? (I don't really want to do that)

**Comment by JasonMcRay** [comment]
Accepting as workaround fix.
Reported to IC2: http://bt.industrial-craft.net/view.php?id=1827

**Pull request merged**
