### PR TITLE
[New Mod] Steve's Carts 2

### PR DESCRIPTION
**Pull request by DarknessShadow**
Steve's Carts 2 is a really cool mod adding customizable minecarts that can do (crop and tree) farming, mining and much more!
You said the only reason we don't have Steve's Carts 2 is because you don't have time so I greggified it :)

### CODE REVIEW

**Comment by JasonMcRay** [comment]
Thanks :)

**Comment by Xavion3** [comment]
So I've downloaded the recipes and they look pretty good, I'd probably have tried more use of GT machines to craft but that's a minor issue at best. My biggest reaction was that hardened and galgadorian metal seem a bit far back and expensive, although hardened metal doesn't seem as extreme as making galgadorian require mass wither slaughter and a fusion reactor before it's obtainable. I mean you have four items which require galgadorian metal with the primary benefit just being that they don't break, which makes the 24 osmium and 1.5 nether stars per galgadorian metal seem rather pricy, everything else is far lower in price than those, although by the time you've got the fusion reactor for the europium they shouldn't be so much of a concern.

Sorry it's a bit rambly but I do think they are made too expensive for their results, it's far, far easier, faster, and cheaper to build the perpetually running alternatives to the galgadorian items and even the reinforced metal doesn't hold up so well given how much you need and that it requires nearly 6 tungstensteel and an industrial diamond per ingot of the stuff.

Maybe lower the costs and put them in various machines? Hardener could be a chemical reactor recipe with obsidian and tungsten dust for example, reinforced and galgadorian could require the EBF to smelt, the PCBs could be assembler recipes similar to the rest of the circuits, iron blades could be made from iron turbine blades, the dynamite carrier could use IC2 dynamite, stuff like that where it encourages breadth of machines over just increasing costs. Although as said it's mainly just reinforced and galgadorian metal I really think are too expensive for what they provide.

**Comment by Timeslice42** [comment]
I love Steve's Carts 2, it was a core part of my 1.6 Universal Electricity pack, but why in the world would we need yet another mod for mining, smelting, harvesting, and mob grinding? This is an even more bizarre addition than Pneumaticraft was.

And don't forget this is a VSWE mod, so that means no support as well, unless it's gone open source. Have you tested to see if the vein miner works on GT ores?

**Comment by Xavion3** [comment]
3.2 is nearly out so I was looking at the changes that were in and this was one of them, as it should be looked at before being thrown in and hopefully 3.2 is out within a week or two so I was looking at the changes. Perfectly valid to say you don't think the mod should be in.

Personally I consider Steve's Carts to be a strong contender for most poorly balanced mod ever made, but that's mainly because I hate time as a balancing mechanic and the mod is basically built around time as a balancing mechanic. I mean in this case it would be all like yay! I built the fusion reactor, got the europium, mined a half dozen iridium veins for the dozen stacks of osmium, and got the triple digit requirements of nether stars so I can build my super galgadorian miner. And I have to wait four hours for it to be done even with every speed upgrade. Yay.

**Comment by Timeslice42** [comment]
Don't forget the part where, even with the "invincibility" shielding, you can still end up losing that cart...

**Comment by JasonMcRay** [comment]
Recreated PR:

https://github.com/JasonMcRay/InfiTech-1.7/pull/490

**Pull request closed without merging**
