### PR TITLE
Dob activation

### PR DESCRIPTION
**Pull request by JasonMcRay**

### CODE REVIEW

**Comment by immibis** [comment]
... what is DOB and *why*?

**Comment by Xavion3** [comment]
A custom bee for the modpack as kind of an endgame goody, I can't recall the reason for the name at all. I think the name may be based off a similar bee from Beyond Reality?

**Comment by JasonMcRay** [comment]
It is indeed end-game bee, that can produce all kinds of nuggets directly
(like 27 or something like that). It is based on bee from Beyond Reality
and DOB stands for "Dimethoxybromoamphetamine" which is Psychadelic Drug -
so basicaly it is a bee on drugs.

here you can find the script for the centrifuging:
https://github.com/JasonMcRay/InfiTech-1.7/blob/master/scripts/forestry.zs#L557
and as you can see, there is a lot.
Web resu

**Comment by immibis** [comment]
NEI only shows the first 9 centrifuge outputs which is why I was a bit confused about this feature. I hope it's in the quest book somewhere that I haven't gotten to yet.

**Comment by JasonMcRay** [comment]
That's limitation of NEI, and we did not put any bee related quests in.

**Comment by immibis** [comment]
Seems very obscure then, unfortunately. You have to accidentally encounter it in NEI to know it exists. And NEI (the only way you would know what it does) doesn't really tell you what it does.

**Pull request merged**
