### PR TITLE
Remove all coloured pipe recipes

### PR DESCRIPTION
**Pull request by Xavion3**

### CODE REVIEW

**Comment by DarknessShadow** [comment]
Why?

**Comment by Xavion3** [comment]
Because currently they're craftable with the normal pipe recipe basically defeating the point of modifying pipe recipes at all?

**Comment by JasonMcRay** [comment]
Gonna take this. Defautl recipes MUST be gone... Will add different ways for those of you who are fancy :)
WIP DO NOT MERGE :D

**Comment by JasonMcRay** [comment]
Ok I think that should be all.
@Xavion3 can you check if I havent missed any? Better to have more ppl to look into it.

**Comment by Xavion3** [comment]
Didn't know you could colour structure pipes, nifty though. Anyway you missed wood, cobblestone, stone, sandstone, and clay fluid pipes from my look.

**Comment by JasonMcRay** [comment]
The T1 pipes (stone,cobble,...) are meant to be easy. So the crafting of them should be colored transport pipe + sealant. As are the non colored fluid pipes. If they are different than that, let me know

**Comment by JasonMcRay** [comment]
Ok I think that might be all.

**Pull request merged**
